from reportlab.platypus import Paragraph, Spacer, Table
from reportlab.lib.units import inch
from datetime import datetime

from .styles import (
    title_style,
    heading_style,
    normal_style,
    disclaimer_style,
    footer_style,
    patient_table_style,
    lab_table_style
)

DISCLAIMER = (
    "This report is AI-generated and intended for informational "
    "purposes only. Please consult your doctor."
)


def build_story(story, data):

    # ---------------- TITLE ----------------
    story.append(Paragraph("AI Medical Report Summary", title_style))
    story.append(Spacer(1, 0.2 * inch))

    # ---------------- PATIENT DETAILS ----------------
    story.append(Paragraph("Patient Information", heading_style))

    patient_table = Table([
        ["Patient Name", data.get("patient_name", "N/A")],
        ["Age", data.get("age", "N/A")],
        ["Gender", data.get("gender", "N/A")],
        ["Report Type", data.get("report_type", "N/A")],
    ], colWidths=[150, 250])

    patient_table.setStyle(patient_table_style())

    story.append(patient_table)
    story.append(Spacer(1, 0.25 * inch))

    # ---------------- SUMMARY ----------------
    story.append(Paragraph("Summary", heading_style))

    story.append(
        Paragraph(
            data.get("summary", "No summary available."),
            normal_style
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    # ---------------- LAB VALUES ----------------
    lab_values = data.get("lab_values", [])

    if lab_values:

        story.append(Paragraph("Key Lab Values", heading_style))

        table_data = [["Test", "Value", "Status"]]

        for item in lab_values:

            table_data.append([
                item.get("test", ""),
                item.get("value", ""),
                item.get("status", "")
            ])

        table = Table(table_data)

        table.setStyle(lab_table_style())

        story.append(table)

        story.append(Spacer(1, 0.25 * inch))

    # ---------------- RECOMMENDATIONS ----------------
    recommendations = data.get("recommendations", [])

    if recommendations:

        story.append(Paragraph("Recommendations", heading_style))

        for item in recommendations:

            story.append(
                Paragraph(
                    "• " + item,
                    normal_style
                )
            )

        story.append(Spacer(1, 0.2 * inch))

    # ---------------- DIET ----------------
    diet = data.get("diet", [])

    if diet:

        story.append(Paragraph("Diet", heading_style))

        for item in diet:

            story.append(
                Paragraph(
                    "• " + item,
                    normal_style
                )
            )

        story.append(Spacer(1, 0.2 * inch))

    # ---------------- LIFESTYLE ----------------
    lifestyle = data.get("lifestyle", [])

    if lifestyle:

        story.append(Paragraph("Lifestyle", heading_style))

        for item in lifestyle:

            story.append(
                Paragraph(
                    "• " + item,
                    normal_style
                )
            )

        story.append(Spacer(1, 0.2 * inch))

    # ---------------- FOLLOW-UP ----------------
    follow_up = data.get("follow_up", [])

    if follow_up:

        story.append(Paragraph("Follow-Up", heading_style))

        for item in follow_up:

            story.append(
                Paragraph(
                    "• " + item,
                    normal_style
                )
            )

        story.append(Spacer(1, 0.2 * inch))

    # ---------------- DISCLAIMER ----------------
    story.append(Paragraph("Disclaimer", heading_style))

    story.append(
        Paragraph(
            DISCLAIMER,
            disclaimer_style
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    # ---------------- FOOTER ----------------
    story.append(
        Paragraph(
            "Generated on: " +
            datetime.now().strftime("%d %B %Y %I:%M %p"),
            footer_style
        )
    )

    story.append(
        Paragraph(
            "Generated by AI Medical Report Summarizer",
            footer_style
        )
    )